### ISSUE TITLE
Panic with wayland and nvidia

### ISSUE THREAD

**Issue by MTFT-Games** [MTFT-Games/void-break-reborn#1]
On Linux, in wayland with default integrated gpu drivers, it will not work without the wayland feature enabled for bevy. With nvidia drivers and using the nvidia card, still on wayland, it will not work unless the wayland feature is removed (appears to then work through Xwayland but not sure then why it wouldn't work without wayland feature on igpu).

Believed to be related to upstream issue https://github.com/gfx-rs/wgpu/issues/2519

**Comment by MTFT-Games** [comment]
```
    Finished dev [optimized + debuginfo] target(s) in 0.16s
     Running `target/debug/void-break-reborn`
2024-01-02T03:41:01.856065Z  INFO bevy_winit::system: Creating new window "Void Break" (0v0)
2024-01-02T03:41:01.858514Z ERROR log: XDG Settings Portal did not return response in time: timeout: 100ms, key: color-scheme    
2024-01-02T03:41:01.954626Z  INFO bevy_render::renderer: AdapterInfo { name: "Quadro P2000", vendor: 4318, device: 7354, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "545.29.06", backend: Vulkan }
ALSA lib pcm_dmix.c:1000:(snd_pcm_dmix_open) unable to open slave
thread 'main' panicked at /home/mtft/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.17.2/src/backend/direct.rs:771:18:
Error in Surface::configure: Validation Error

Caused by:
    Parent device is lost

stack backtrace:
   0: rust_begin_unwind
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:72:14
   2: wgpu::backend::direct::Context::handle_error_fatal
             at /home/mtft/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.17.2/src/backend/direct.rs:345:9
   3: <wgpu::backend::direct::Context as wgpu::context::Context>::surface_configure
             at /home/mtft/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.17.2/src/backend/direct.rs:771:13
   4: <T as wgpu::context::DynContext>::surface_configure
             at /home/mtft/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.17.2/src/context.rs:2174:9
   5: wgpu::Surface::configure
             at /home/mtft/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.17.2/src/lib.rs:4601:9
   6: bevy_render::renderer::render_device::RenderDevice::configure_surface
             at /home/mtft/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_render-0.12.1/src/renderer/render_device.rs:187:9
   7: bevy_render::view::window::prepare_windows
             at /home/mtft/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_render-0.12.1/src/view/window/mod.rs:359:13
   8: core::ops::function::FnMut::call_mut
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:166:5
   9: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:294:13
  10: <Func as bevy_ecs::system::function_system::SystemParamFunction<fn(F0,F1,F2,F3,F4,F5,F6,F7,F8,F9) .> Out>>::run::call_inner
             at /home/mtft/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.12.1/src/system/function_system.rs:642:21
  11: <Func as bevy_ecs::system::function_system::SystemParamFunction<fn(F0,F1,F2,F3,F4,F5,F6,F7,F8,F9) .> Out>>::run
             at /home/mtft/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.12.1/src/system/function_system.rs:645:17
  12: <bevy_ecs::system::function_system::FunctionSystem<Marker,F> as bevy_ecs::system::system::System>::run_unsafe
             at /home/mtft/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.12.1/src/system/function_system.rs:485:19
  13: bevy_ecs::schedule::executor::multi_threaded::MultiThreadedExecutor::spawn_system_task::{{closure}}::{{closure}}
             at /home/mtft/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.12.1/src/schedule/executor/multi_threaded.rs:505:26
  14: core::ops::function::FnOnce::call_once
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:250:5
  15: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panic/unwind_safe.rs:272:9
  16: std::panicking::try::do_call
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:552:40
  17: std::panicking::try
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:516:19
  18: std::panic::catch_unwind
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panic.rs:142:14
  19: bevy_ecs::schedule::executor::multi_threaded::MultiThreadedExecutor::spawn_system_task::{{closure}}
             at /home/mtft/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.12.1/src/schedule/executor/multi_threaded.rs:500:23
  20: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::future::future::Future>::poll
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panic/unwind_safe.rs:297:9
  21: <futures_lite::future::CatchUnwind<F> as core::future::future::Future>::poll::{{closure}}
             at /home/mtft/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-lite-1.13.0/src/future.rs:626:42
  22: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panic/unwind_safe.rs:272:9
  23: std::panicking::try::do_call
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:552:40
  24: std::panicking::try
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:516:19
  25: std::panic::catch_unwind
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panic.rs:142:14
  26: <futures_lite::future::CatchUnwind<F> as core::future::future::Future>::poll
             at /home/mtft/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-lite-1.13.0/src/future.rs:626:9
  27: async_executor::Executor::spawn::{{closure}}
             at /home/mtft/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-executor-1.8.0/src/lib.rs:158:20
  28: async_task::raw::RawTask<F,T,S,M>::run::{{closure}}
             at /home/mtft/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-task-4.6.0/src/raw.rs:557:21
  29: core::ops::function::FnOnce::call_once
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:250:5
  30: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panic/unwind_safe.rs:272:9
  31: std::panicking::try::do_call
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:552:40
  32: std::panicking::try
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:516:19
  33: std::panic::catch_unwind
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panic.rs:142:14
  34: async_task::raw::RawTask<F,T,S,M>::run
             at /home/mtft/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-task-4.6.0/src/raw.rs:556:23
  35: async_task::runnable::Runnable<M>::run
             at /home/mtft/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-task-4.6.0/src/runnable.rs:784:18
  36: async_executor::Executor::tick::{{closure}}
             at /home/mtft/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-executor-1.8.0/src/lib.rs:227:9
  37: bevy_tasks::thread_executor::ThreadExecutorTicker::tick::{{closure}}
             at /home/mtft/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_tasks-0.12.1/src/thread_executor.rs:105:39
  38: bevy_tasks::task_pool::TaskPool::execute_global_scope::{{closure}}::{{closure}}::{{closure}}
             at /home/mtft/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_tasks-0.12.1/src/task_pool.rs:491:45
  39: <futures_lite::future::Or<F1,F2> as core::future::future::Future>::poll
             at /home/mtft/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-lite-2.1.0/src/future.rs:446:33
  40: async_executor::Executor::run::{{closure}}
             at /home/mtft/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-executor-1.8.0/src/lib.rs:261:32
  41: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::future::future::Future>::poll
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panic/unwind_safe.rs:297:9
  42: <futures_lite::future::CatchUnwind<F> as core::future::future::Future>::poll::{{closure}}
             at /home/mtft/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-lite-1.13.0/src/future.rs:626:42
  43: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panic/unwind_safe.rs:272:9
  44: std::panicking::try::do_call
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:552:40
  45: std::panicking::try
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:516:19
  46: std::panic::catch_unwind
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panic.rs:142:14
  47: <futures_lite::future::CatchUnwind<F> as core::future::future::Future>::poll
             at /home/mtft/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-lite-1.13.0/src/future.rs:626:9
  48: bevy_tasks::task_pool::TaskPool::execute_global_scope::{{closure}}::{{closure}}
             at /home/mtft/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_tasks-0.12.1/src/task_pool.rs:496:22
  49: <futures_lite::future::Or<F1,F2> as core::future::future::Future>::poll
             at /home/mtft/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-lite-1.13.0/src/future.rs:526:33
  50: bevy_tasks::task_pool::TaskPool::execute_global_scope::{{closure}}
             at /home/mtft/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_tasks-0.12.1/src/task_pool.rs:500:41
  51: bevy_tasks::task_pool::TaskPool::scope_with_executor_inner::{{closure}}
             at /home/mtft/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_tasks-0.12.1/src/task_pool.rs:427:89
  52: futures_lite::future::block_on::{{closure}}
             at /home/mtft/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-lite-1.13.0/src/future.rs:89:27
  53: std::thread::local::LocalKey<T>::try_with
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/thread/local.rs:270:16
  54: std::thread::local::LocalKey<T>::with
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/thread/local.rs:246:9
  55: futures_lite::future::block_on
             at /home/mtft/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-lite-1.13.0/src/future.rs:79:11
  56: bevy_tasks::task_pool::TaskPool::scope_with_executor_inner
             at /home/mtft/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_tasks-0.12.1/src/task_pool.rs:383:13
  57: bevy_tasks::task_pool::TaskPool::scope_with_executor::{{closure}}
  58: std::thread::local::LocalKey<T>::try_with
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/thread/local.rs:270:16
  59: std::thread::local::LocalKey<T>::with
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/thread/local.rs:246:9
  60: bevy_tasks::task_pool::TaskPool::scope_with_executor
             at /home/mtft/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_tasks-0.12.1/src/task_pool.rs:316:31
  61: bevy_render::pipelined_rendering::update_rendering::{{closure}}
             at /home/mtft/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_render-0.12.1/src/pipelined_rendering.rs:141:30
  62: bevy_ecs::world::World::resource_scope
             at /home/mtft/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.12.1/src/world/mod.rs:1571:22
  63: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/alloc/src/boxed.rs:2021:9
  64: bevy_app::app::SubApp::extract
             at /home/mtft/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_app-0.12.1/src/app.rs:172:9
  65: bevy_app::app::App::update
             at /home/mtft/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_app-0.12.1/src/app.rs:271:13
  66: bevy_winit::winit_runner::{{closure}}
             at /home/mtft/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_winit-0.12.1/src/lib.rs:836:25
  67: winit::platform_impl::platform::sticky_exit_callback
             at /home/mtft/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.7/src/platform_impl/linux/mod.rs:884:9
  68: winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::run_return
             at /home/mtft/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.7/src/platform_impl/linux/wayland/event_loop/mod.rs:508:13
  69: winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::run
             at /home/mtft/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.7/src/platform_impl/linux/wayland/event_loop/mod.rs:223:25
  70: winit::platform_impl::platform::EventLoop<T>::run
             at /home/mtft/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.7/src/platform_impl/linux/mod.rs:792:56
  71: winit::event_loop::EventLoop<T>::run
             at /home/mtft/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.7/src/event_loop.rs:305:9
  72: bevy_winit::run
             at /home/mtft/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_winit-0.12.1/src/lib.rs:235:16
  73: bevy_winit::winit_runner
             at /home/mtft/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_winit-0.12.1/src/lib.rs:920:9
  74: core::ops::function::FnOnce::call_once
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:250:5
  75: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:250:5
  76: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/alloc/src/boxed.rs:2007:9
  77: bevy_app::app::App::run
             at /home/mtft/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_app-0.12.1/src/app.rs:314:9
  78: void_break_reborn::main
             at ./src/main.rs:67:5
  79: core::ops::function::FnOnce::call_once
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Encountered a panic in system `bevy_render::view::window::prepare_windows`!
thread 'Compute Task Pool (0)' panicked at /home/mtft/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_render-0.12.1/src/pipelined_rendering.rs:145:45:
called `Result::unwrap()` on an `Err` value: RecvError
stack backtrace:
   0: rust_begin_unwind
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/result.rs:1653:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/result.rs:1077:23
   4: bevy_render::pipelined_rendering::update_rendering::{{closure}}::{{closure}}::{{closure}}
             at /home/mtft/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_render-0.12.1/src/pipelined_rendering.rs:145:21
   5: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::future::future::Future>::poll
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panic/unwind_safe.rs:297:9
   6: <futures_lite::future::CatchUnwind<F> as core::future::future::Future>::poll::{{closure}}
             at /home/mtft/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-lite-1.13.0/src/future.rs:626:42
   7: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panic/unwind_safe.rs:272:9
   8: std::panicking::try::do_call
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:552:40
   9: std::panicking::try
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:516:19
  10: std::panic::catch_unwind
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panic.rs:142:14
  11: <futures_lite::future::CatchUnwind<F> as core::future::future::Future>::poll
             at /home/mtft/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-lite-1.13.0/src/future.rs:626:9
  12: async_executor::Executor::spawn::{{closure}}
             at /home/mtft/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-executor-1.8.0/src/lib.rs:158:20
  13: async_task::raw::RawTask<F,T,S,M>::run::{{closure}}
             at /home/mtft/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-task-4.6.0/src/raw.rs:557:21
  14: core::ops::function::FnOnce::call_once
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:250:5
  15: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panic/unwind_safe.rs:272:9
  16: std::panicking::try::do_call
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:552:40
  17: std::panicking::try
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:516:19
  18: std::panic::catch_unwind
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panic.rs:142:14
  19: async_task::raw::RawTask<F,T,S,M>::run
             at /home/mtft/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-task-4.6.0/src/raw.rs:556:23
  20: async_task::runnable::Runnable<M>::run
             at /home/mtft/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-task-4.6.0/src/runnable.rs:784:18
  21: async_executor::Executor::run::{{closure}}::{{closure}}
             at /home/mtft/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-executor-1.8.0/src/lib.rs:254:21
  22: <futures_lite::future::Or<F1,F2> as core::future::future::Future>::poll
             at /home/mtft/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-lite-2.1.0/src/future.rs:449:33
  23: async_executor::Executor::run::{{closure}}
             at /home/mtft/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-executor-1.8.0/src/lib.rs:261:32
  24: futures_lite::future::block_on::{{closure}}
             at /home/mtft/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-lite-1.13.0/src/future.rs:89:27
  25: std::thread::local::LocalKey<T>::try_with
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/thread/local.rs:270:16
  26: std::thread::local::LocalKey<T>::with
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/thread/local.rs:246:9
  27: futures_lite::future::block_on
             at /home/mtft/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-lite-1.13.0/src/future.rs:79:11
  28: bevy_tasks::task_pool::TaskPool::new_internal::{{closure}}::{{closure}}::{{closure}}::{{closure}}
             at /home/mtft/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_tasks-0.12.1/src/task_pool.rs:180:37
  29: std::panicking::try::do_call
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:552:40
  30: std::panicking::try
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:516:19
  31: std::panic::catch_unwind
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panic.rs:142:14
  32: bevy_tasks::task_pool::TaskPool::new_internal::{{closure}}::{{closure}}::{{closure}}
             at /home/mtft/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_tasks-0.12.1/src/task_pool.rs:174:43
  33: std::thread::local::LocalKey<T>::try_with
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/thread/local.rs:270:16
  34: std::thread::local::LocalKey<T>::with
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/thread/local.rs:246:9
  35: bevy_tasks::task_pool::TaskPool::new_internal::{{closure}}::{{closure}}
             at /home/mtft/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_tasks-0.12.1/src/task_pool.rs:167:50
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: queue 0x56407c5c1110 destroyed while proxies still attached:
  xdg_wm_base@20 still attached
  wl_output@14 still attached
  wl_seat@13 still attached
  xdg_activation_v1@12 still attached
  wp_viewporter@11 still attached
  zwp_text_input_manager_v3@10 still attached
  zwp_pointer_constraints_v1@9 still attached
  zwp_relative_pointer_manager_v1@8 still attached
  zxdg_decoration_manager_v1@7 still attached
  wl_subcompositor@6 still attached
  wl_compositor@5 still attached
  wl_shm@4 still attached
  wl_registry@2 still attached
```

**Comment by MTFT-Games** [comment]
Not sure what changed or what I did but now with the wayland feature enabled instead of panic, it will start extremely slowly and then run at 0 fps. So effectively it will just hang after loading assets...
